sudo: false

language: python

python:
  - 2.7

install:
  
  - sudo apt-get install python-dev python-setuptools python-numpy python-bsddb3 subversion build-essential python-imaging db-util git


  - sudo apt-get install emacs htop 


  - sudo easy_install "pyramid==1.4.5" 
  - sudo easy_install "pyramid-persona==1.5"
  - pip install codecov
  - pip install "selenium==2.53.2"

  - cd
  - svn checkout svn://r-forge.r-project.org/svnroot/segannot/python segannot
  - cd segannot
  - python setup.py build
  - sudo python setup.py install

  - cd
  - git clone https://github.com/tdhock/SegAnnDB.git
  - cd SegAnnDB
  - sed -i 's#^FILE_PREFIX.*$#FILE_PREFIX = "/var/www"#' plotter/db.py
  - sudo python setup.py install
  - sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - tar xvzf geckodriver-v0.19.1-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - sudo apt-get install apache2 libapache2-mod-wsgi
  - cd /var/www
  - sudo chown www-data .
  - sudo -u www-data mkdir db secret chromlength
  - sudo cp ~/SegAnnDB/apache.config /etc/apache2/sites-available/pyramid.conf
  - sudo a2enmod wsgi
  - sudo a2dissite 000-default
  - sudo a2ensite pyramid
  - cd ~/SegAnnDB
  - bash server-recover-restart.sh
  - sudo wget -O /var/www/chromlength/hg19.txt.gz http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/chromInfo.txt.gz
  - mkdir db secret chromlength
  - bash recover-restart.sh
script:
  - coverage run tests/tests.py
  - bash <(curl -s https://codecov.io/bash) -cF python
