sudo: false

language: python

python:
  - 2.7

install:
  
  - sudo apt-get install python-dev python-setuptools python-numpy python-bsddb3 subversion build-essential python-imaging db-util git


  - sudo apt-get install emacs htop 


  - sudo easy_install "pyramid==1.4.5" 
  - sudo easy_install "pyramid-persona==1.5"
  - pip install codecov
  - pip install "selenium==2.53.2"

  - cd
  - svn checkout svn://r-forge.r-project.org/svnroot/segannot/python segannot
  - cd segannot
  - python setup.py build
  - sudo python setup.py install

  - cd
  - git clone https://github.com/tdhock/SegAnnDB.git
  - cd SegAnnDB
  - sed -i 's#^FILE_PREFIX.*$#FILE_PREFIX = "/var/www"#' plotter/db.py
  - sudo python setup.py install

script:
  - coverage run tests/tests.py

after_success:
- codecov
